package com.maple.web.carserver.mapper;

import com.maple.web.carserver.domain.NewsEntity;

import java.util.List;

public interface NewsEntityMapper {

    /**
     * 新闻总数
     *
     * @return
     */
    Integer count();

    /**
     * 分页获取新闻
     *
     * @param pageNumber
     * @return
     */
    List<NewsEntity> selectNewsByPageNumber(Integer pageNumber);

    NewsEntity getNewsDetail(Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Wed Mar 21 16:07:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Wed Mar 21 16:07:47 CST 2018
     */
    int insert(NewsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Wed Mar 21 16:07:47 CST 2018
     */
    int insertSelective(NewsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Wed Mar 21 16:07:47 CST 2018
     */
    NewsEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Wed Mar 21 16:07:47 CST 2018
     */
    int updateByPrimaryKeySelective(NewsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Wed Mar 21 16:07:47 CST 2018
     */
    int updateByPrimaryKey(NewsEntity record);
}