package com.maple.web.carserver.mapper;

import com.maple.web.carserver.domain.PurchaseEntity;

public interface PurchaseEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_purchase
     *
     * @mbg.generated Wed Mar 21 16:07:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_purchase
     *
     * @mbg.generated Wed Mar 21 16:07:47 CST 2018
     */
    int insert(PurchaseEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_purchase
     *
     * @mbg.generated Wed Mar 21 16:07:47 CST 2018
     */
    int insertSelective(PurchaseEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_purchase
     *
     * @mbg.generated Wed Mar 21 16:07:47 CST 2018
     */
    PurchaseEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_purchase
     *
     * @mbg.generated Wed Mar 21 16:07:47 CST 2018
     */
    int updateByPrimaryKeySelective(PurchaseEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_purchase
     *
     * @mbg.generated Wed Mar 21 16:07:47 CST 2018
     */
    int updateByPrimaryKey(PurchaseEntity record);
}