package com.maple.web.carserver.mapper;

import com.maple.web.carserver.domain.ReportEntity;
import com.maple.web.carserver.domain.UserEntity;

import java.util.List;

public interface ReportEntityMapper {


    /**
     * 用户数
     * @return
     */
    Integer count();


    /**
     *  用户列表
     * @param start
     * @return
     */
    List<UserEntity> selectUserList(Integer start);

    /**
     * 获取单个用户问卷结果
     * @param userId
     * @return
     */
    List<ReportEntity> selectByUserId(Integer userId);

    /**
     * 全部结果，用于图表
     * @return
     */
    List<ReportEntity> getReportResult();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbg.generated Wed Mar 21 16:07:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbg.generated Wed Mar 21 16:07:47 CST 2018
     */
    int insert(ReportEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbg.generated Wed Mar 21 16:07:47 CST 2018
     */
    int insertSelective(ReportEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbg.generated Wed Mar 21 16:07:47 CST 2018
     */
    ReportEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbg.generated Wed Mar 21 16:07:47 CST 2018
     */
    int updateByPrimaryKeySelective(ReportEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbg.generated Wed Mar 21 16:07:47 CST 2018
     */
    int updateByPrimaryKey(ReportEntity record);
}