package com.maple.web.carserver.mapper;

import com.maple.web.carserver.dao.ShoppingCartDao;
import com.maple.web.carserver.domain.ShoppingCartEntity;

import java.util.List;

public interface ShoppingCartEntityMapper {

    /**
     * 获取某个用户购物车商品
     *
     * @param userId
     * @return
     */
    Integer count(Integer userId);

    /**
     * 获取某个用户购物车商品
     *
     * @param userId
     * @return
     */
    List<ShoppingCartDao> selectGoodsList(Integer userId);

    List<ShoppingCartDao> getByIdList(List<String> idList);

    /**
     * 获取是否已经将某商品加入购物车
     * @param record
     * @return
     */
    ShoppingCartEntity selectByGoodsId(ShoppingCartEntity record);

    Integer buyAllGoods(String[] cartIdList);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shopping_cart
     *
     * @mbg.generated Sat Mar 24 14:31:40 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shopping_cart
     *
     * @mbg.generated Sat Mar 24 14:31:40 CST 2018
     */
    int insert(ShoppingCartEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shopping_cart
     *
     * @mbg.generated Sat Mar 24 14:31:40 CST 2018
     */
    int insertSelective(ShoppingCartEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shopping_cart
     *
     * @mbg.generated Sat Mar 24 14:31:40 CST 2018
     */
    ShoppingCartEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shopping_cart
     *
     * @mbg.generated Sat Mar 24 14:31:40 CST 2018
     */
    int updateByPrimaryKeySelective(ShoppingCartEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shopping_cart
     *
     * @mbg.generated Sat Mar 24 14:31:40 CST 2018
     */
    int updateByPrimaryKey(ShoppingCartEntity record);
}