package com.maple.web.carserver.domain;

import java.util.Date;

public class FinanceEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_finance.id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_finance.amount
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_finance.type
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_finance.create_time
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_finance.remark
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_finance.user
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private String user;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_finance.id
     *
     * @return the value of tb_finance.id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_finance.id
     *
     * @param id the value for tb_finance.id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_finance.amount
     *
     * @return the value of tb_finance.amount
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_finance.amount
     *
     * @param amount the value for tb_finance.amount
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_finance.type
     *
     * @return the value of tb_finance.type
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_finance.type
     *
     * @param type the value for tb_finance.type
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_finance.create_time
     *
     * @return the value of tb_finance.create_time
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_finance.create_time
     *
     * @param createTime the value for tb_finance.create_time
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_finance.remark
     *
     * @return the value of tb_finance.remark
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_finance.remark
     *
     * @param remark the value for tb_finance.remark
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_finance.user
     *
     * @return the value of tb_finance.user
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_finance.user
     *
     * @param user the value for tb_finance.user
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }
}