package com.maple.web.carserver.domain;

import java.util.Date;

public class NewsEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.title
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.create_time
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.content
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.id
     *
     * @return the value of tb_news.id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.id
     *
     * @param id the value for tb_news.id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.title
     *
     * @return the value of tb_news.title
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.title
     *
     * @param title the value for tb_news.title
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.create_time
     *
     * @return the value of tb_news.create_time
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.create_time
     *
     * @param createTime the value for tb_news.create_time
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.content
     *
     * @return the value of tb_news.content
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.content
     *
     * @param content the value for tb_news.content
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}