package com.maple.web.carserver.domain;

import java.util.Date;

public class PurchaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_purchase.id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_purchase.car_type
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private String carType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_purchase.introduction
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_purchase.car_status
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private Byte carStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_purchase.create_time
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_purchase.id
     *
     * @return the value of tb_purchase.id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_purchase.id
     *
     * @param id the value for tb_purchase.id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_purchase.car_type
     *
     * @return the value of tb_purchase.car_type
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_purchase.car_type
     *
     * @param carType the value for tb_purchase.car_type
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_purchase.introduction
     *
     * @return the value of tb_purchase.introduction
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_purchase.introduction
     *
     * @param introduction the value for tb_purchase.introduction
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_purchase.car_status
     *
     * @return the value of tb_purchase.car_status
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public Byte getCarStatus() {
        return carStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_purchase.car_status
     *
     * @param carStatus the value for tb_purchase.car_status
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setCarStatus(Byte carStatus) {
        this.carStatus = carStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_purchase.create_time
     *
     * @return the value of tb_purchase.create_time
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_purchase.create_time
     *
     * @param createTime the value for tb_purchase.create_time
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}