package com.maple.web.carserver.domain;

public class ReportEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_report.id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_report.tb_user_id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private Integer tbUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_report.question_id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_report.answer
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.id
     *
     * @return the value of tb_report.id
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.id
     *
     * @param id the value for tb_report.id
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.tb_user_id
     *
     * @return the value of tb_report.tb_user_id
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public Integer getTbUserId() {
        return tbUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.tb_user_id
     *
     * @param tbUserId the value for tb_report.tb_user_id
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setTbUserId(Integer tbUserId) {
        this.tbUserId = tbUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.question_id
     *
     * @return the value of tb_report.question_id
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.question_id
     *
     * @param questionId the value for tb_report.question_id
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.answer
     *
     * @return the value of tb_report.answer
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.answer
     *
     * @param answer the value for tb_report.answer
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    public ReportEntity() {
    }

    public ReportEntity(Integer tbUserId, Integer questionId, String answer) {
        this.tbUserId = tbUserId;
        this.questionId = questionId;
        this.answer = answer;
    }
}