package com.maple.web.carserver.domain;

import java.util.Date;

public class ShoppingCartEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shopping_cart.id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shopping_cart.tb_user_id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private Integer tbUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shopping_cart.tb_goods_id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private Integer tbGoodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shopping_cart.count
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shopping_cart.create_time
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shopping_cart.is_sale
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private Byte isSale;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shopping_cart.id
     *
     * @return the value of tb_shopping_cart.id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shopping_cart.id
     *
     * @param id the value for tb_shopping_cart.id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shopping_cart.tb_user_id
     *
     * @return the value of tb_shopping_cart.tb_user_id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public Integer getTbUserId() {
        return tbUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shopping_cart.tb_user_id
     *
     * @param tbUserId the value for tb_shopping_cart.tb_user_id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setTbUserId(Integer tbUserId) {
        this.tbUserId = tbUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shopping_cart.tb_goods_id
     *
     * @return the value of tb_shopping_cart.tb_goods_id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public Integer getTbGoodsId() {
        return tbGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shopping_cart.tb_goods_id
     *
     * @param tbGoodsId the value for tb_shopping_cart.tb_goods_id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setTbGoodsId(Integer tbGoodsId) {
        this.tbGoodsId = tbGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shopping_cart.count
     *
     * @return the value of tb_shopping_cart.count
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shopping_cart.count
     *
     * @param count the value for tb_shopping_cart.count
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shopping_cart.create_time
     *
     * @return the value of tb_shopping_cart.create_time
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shopping_cart.create_time
     *
     * @param createTime the value for tb_shopping_cart.create_time
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shopping_cart.is_sale
     *
     * @return the value of tb_shopping_cart.is_sale
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public Byte getIsSale() {
        return isSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shopping_cart.is_sale
     *
     * @param isSale the value for tb_shopping_cart.is_sale
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setIsSale(Byte isSale) {
        this.isSale = isSale;
    }
}