package com.maple.web.carserver.domain;

import java.util.Date;

public class StoreEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_store.id
     *
     * @mbg.generated Tue Apr 17 22:42:23 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_store.count
     *
     * @mbg.generated Tue Apr 17 22:42:23 CST 2018
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_store.tb_goods_id
     *
     * @mbg.generated Tue Apr 17 22:42:23 CST 2018
     */
    private Integer tbGoodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_store.create_time
     *
     * @mbg.generated Tue Apr 17 22:42:23 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_store.id
     *
     * @return the value of tb_store.id
     *
     * @mbg.generated Tue Apr 17 22:42:23 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_store.id
     *
     * @param id the value for tb_store.id
     *
     * @mbg.generated Tue Apr 17 22:42:23 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_store.count
     *
     * @return the value of tb_store.count
     *
     * @mbg.generated Tue Apr 17 22:42:23 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_store.count
     *
     * @param count the value for tb_store.count
     *
     * @mbg.generated Tue Apr 17 22:42:23 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_store.tb_goods_id
     *
     * @return the value of tb_store.tb_goods_id
     *
     * @mbg.generated Tue Apr 17 22:42:23 CST 2018
     */
    public Integer getTbGoodsId() {
        return tbGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_store.tb_goods_id
     *
     * @param tbGoodsId the value for tb_store.tb_goods_id
     *
     * @mbg.generated Tue Apr 17 22:42:23 CST 2018
     */
    public void setTbGoodsId(Integer tbGoodsId) {
        this.tbGoodsId = tbGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_store.create_time
     *
     * @return the value of tb_store.create_time
     *
     * @mbg.generated Tue Apr 17 22:42:23 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_store.create_time
     *
     * @param createTime the value for tb_store.create_time
     *
     * @mbg.generated Tue Apr 17 22:42:23 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}