package com.maple.web.carserver.domain;

import java.util.Date;

public class UserEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.username
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_pwd
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private String userPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.is_vip
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private Byte isVip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.is_admin
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private Byte isAdmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.create_time
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.integral
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    private String integral;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.id
     *
     * @return the value of tb_user.id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.id
     *
     * @param id the value for tb_user.id
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.username
     *
     * @return the value of tb_user.username
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.username
     *
     * @param username the value for tb_user.username
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_pwd
     *
     * @return the value of tb_user.user_pwd
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_pwd
     *
     * @param userPwd the value for tb_user.user_pwd
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.is_vip
     *
     * @return the value of tb_user.is_vip
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public Byte getIsVip() {
        return isVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.is_vip
     *
     * @param isVip the value for tb_user.is_vip
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setIsVip(Byte isVip) {
        this.isVip = isVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.is_admin
     *
     * @return the value of tb_user.is_admin
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public Byte getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.is_admin
     *
     * @param isAdmin the value for tb_user.is_admin
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setIsAdmin(Byte isAdmin) {
        this.isAdmin = isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.create_time
     *
     * @return the value of tb_user.create_time
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.create_time
     *
     * @param createTime the value for tb_user.create_time
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.integral
     *
     * @return the value of tb_user.integral
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public String getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.integral
     *
     * @param integral the value for tb_user.integral
     *
     * @mbg.generated Wed Mar 28 21:23:26 CST 2018
     */
    public void setIntegral(String integral) {
        this.integral = integral == null ? null : integral.trim();
    }
}